### ISSUE TITLE
Sanitize HTML

### ISSUE THREAD

**Issue by bbengfort** [bbengfort/baleen#13]
Use bleach to sanitize the post HTML to ensure there are no harmful scripts. 

Either on Export or for Mongo storage.

**Comment by echolabstech** [comment]
Looking into this.

**Comment by bbengfort** [comment]
See also #14

**Comment by echolabstech** [comment]
Resolved [here](https://github.com/bbengfort/baleen/commit/2fec1ccff0979699f3948461f0948fc669c37ba6).

Also see [this issue.](https://github.com/bbengfort/baleen/issues/68)

**Comment by bbengfort** [comment]
@echolabstech -- do you want to write some tests and then we can close this issue?

**Comment by janetriley** [comment]
I've written some tests, will submit a PR.

**Comment by echolabstech** [comment]
Thanks for the tests!

**Comment by janetriley** [comment]
Tests are addressed in issue #70.  @echolabstech 's changes were merged, this ticket can be closed.
