### ISSUE TITLE
Quick time display

### ISSUE THREAD

**Issue by bbengfort** [bbengfort/baleen#35]
It would be really helpful to get some "at a glance " times into the application, particularly for duration (finished - started). 
- Add a duration method to `baleen.models.Job` that computes the number of seconds between started and finished (unless not finished, then between now and started). 
- Add the duration to the page colored green if it's less than an hour, yellow if it's less than 5 hours, and red otherwise. 

Iconography from [font awesome](https://fortawesome.github.io/Font-Awesome/) would also help make things stand out!

**Comment by bbengfort** [comment]
Ok, I've added the duration to the model and to the status page - but haven't done the front end work for colorization or iconography.

**Comment by bahadasx** [comment]
I can take a look at this.

**Comment by bbengfort** [comment]
@bahadasx awesome thanks -- have you seen the new front end? I had some debugging issues I had to deal with, and figured I mind as well just put the helpers I was looking at onto the status page.

Note also that you have direct access to the repo now; so please be sure to branch from develop and to merge into develop!

**Comment by bahadasx** [comment]
I did see the new front end.  It looks great and I think it was a good idea to split the logs out into its own page.

**Comment by bahadasx** [comment]
@bbengfort What are your thoughts on iconography?  Are you thinking along the lines of having an icon next to the label for each cell?

**Comment by bahadasx** [comment]
@bbengfort FYI, I made a PR to address this issue but somehow it ended up as a new issue #42.

**Comment by bbengfort** [comment]
@bahadasx my thoughts are basically that the icons give a quick visual indication of what's happening in the system, and allow you to symbolically look up the information you want faster (right now you just have to read through everything). If it looks good I think it will work, so an icon next to the label or in its own cell would work fine!

**Comment by bbengfort** [comment]
So this is closed by PR #42? (Pull requests are just issues)

**Comment by bahadasx** [comment]
I did not address the iconography, so you can leave it open until I address that if you like.

**Comment by bbengfort** [comment]
Ok - sorted; thanks!
