### ISSUE TITLE
Trouble getting installing feedparser

### ISSUE THREAD

**Issue by bahadasx** [bbengfort/baleen#40]
@bbengfort I'm having trouble pip installing feedparser from the requirements.txt.  Here is the error I'm getting:

Collecting feedparser==5.2.1 (from -r requirements.txt (line 2))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f26add79990>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/feedparser/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f26add79b10>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/feedparser/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f26add79c90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/feedparser/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f26add79e10>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/feedparser/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f26add79f90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/feedparser/
  Could not find a version that satisfies the requirement feedparser==5.2.1 (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for feedparser==5.2.1 (from -r requirements.txt (line 2))
ERROR: Service 'app' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

**Comment by bahadasx** [comment]
Resolved itself!  I think it was an issue with the firewall setup on the network I was operating on

**Comment by bbengfort** [comment]
Hehe, good - I was about to say that's quite the pickle, since I couldn't
figure it out. However, it does look like a connection error in that it
cannot make web requests to the pip endpoint.
