### ISSUE TITLE
Docker image is empty

### ISSUE THREAD

**Issue by janetriley** [bbengfort/baleen#53]
After connecting to the docker image, all I see is the requirements.txt folder.

To reproduce:
- Follow steps 1-3 of the Docker directions on the Quickstart instructions in docs/index.md
- `docker build -t "baleen_app_1" -f Dockerfile-app`
- follow step 4: `docker exec -it baleen_app_1 /bin/bash`

Results:

```
root@05c2ca45b232:/baleen# ls
requirements.txt
```

**Comment by bbengfort** [comment]
@lauralorenz this isn't in my area; would you mind taking a look?

**Comment by lauralorenz** [comment]
1. incredibly awkwardly late response
2. Realize that a really important step is not included in the docker directions which is to start the whole stack with `docker-compose up -d`. It is in that configuration file that [the specification for the local baleen files to be mounted in the container is made](https://github.com/bbengfort/baleen/blob/master/docker-compose.yml#L9).
