### ISSUE TITLE
Update Docker image to Python 3.5

### ISSUE THREAD

**Issue by bbengfort** [bbengfort/baleen#55]
Update the Docker image to use Python 3.5 as Baleen is now dependent solely on Python 3.5

**Comment by lauralorenz** [comment]
Also should add a docs refresh due to the completely missing part regarding starting the stack with `docker-compose` referenced in #53

**Comment by bbengfort** [comment]
@lauralorenz so is this complete with the pull request you submitted?

**Comment by lauralorenz** [comment]
Yes; closes 55 and 53
