### ISSUE TITLE
README Markdown messed up

### ISSUE THREAD

**Issue by bbengfort** [bbengfort/baleen#76]
For some reason the README markdown in the repository is not rendering correctly.

**Comment by will2041** [comment]
Took a few commits, but looks cleaned up:
- https://github.com/DistrictDataLabs/baleen/commit/182181c866607a0cbec2b9a9d6ad51ee106d93b1
- https://github.com/DistrictDataLabs/baleen/commit/4d5d96725d10c5b11a4a5a10887bc98a514bb14f
- https://github.com/DistrictDataLabs/baleen/commit/a070a9a12effa46979a37bf15f679e56944b60ac
- https://github.com/DistrictDataLabs/baleen/commit/c6933bea031a5b72e47f654e20fcd7461137e517
