### ISSUE TITLE
Baleen add2venv

### ISSUE THREAD

**Issue by bbengfort** [bbengfort/baleen#77]
Update instructions to include `add2venv` rather than `echo $(pwd)`

**Comment by janetriley** [comment]
Please assign to me.

**Comment by will2041** [comment]
It's taken me like 20 minutes to figure out I didn't have permissions to do that...

Finally got permissions sorted out, so once you accept the invitation to collaborate, I should be able to assign this to you.

**Comment by janetriley** [comment]
Thanks, I accepted it.

**Comment by janetriley** [comment]
In progress.

**Comment by janetriley** [comment]
`add2virtualenv` is a virtualenvwrapper command.  The instructions are plain vanilla virtualenv. 

I retract the bug; please close it.

**Comment by bbengfort** [comment]
@janetriley well, if you'd like you can make it a `virtualenvwrapper` instruction ... it's 100% up to you. Also are you not able to close the issue? Let me check your permissions.

**Comment by bbengfort** [comment]
@janetriley ok, you should be able to close issues; I've given you `write` permissions to the repository.

**Comment by janetriley** [comment]
I'm going to close this issue.  

The original instructions still work. Python 3.6 has venv built in with the `python3 -m venv /path/to/new/virtual/environment`  command.  I don't know how virtualenvwrapper will fit in with 3.6, and I don't want to offer a path unless I know it will be smooth.
