### ISSUE TITLE
Update baleen github repo url in docs

### ISSUE THREAD

**Issue by janetriley** [bbengfort/baleen#80]
Change github/bbengfort/baleen to github/districtdatalabs/baleen

**Comment by will2041** [comment]
We've got the README updated on the develop branch.  There's still a ton of references that need to be updated in other files. :(

`git grep bbengfort` shows update points

**Comment by janetriley** [comment]
Please assign to me.

**Comment by janetriley** [comment]
This is in progress.  Waffle won't let me move tickets, alas.

**Comment by janetriley** [comment]
Pull request was merged, closing the issue.
