### ISSUE TITLE
PEP8 cleanup

### ISSUE THREAD

**Issue by janetriley** [bbengfort/baleen#83]
PEP8 pointed out many opportunities for improvement.

**Comment by janetriley** [comment]
I can do this over the weekend when the sprint is over, to minimize impact on work in progress.  

Pick me! Pick me!

**Comment by will2041** [comment]
Ha!  Picked.

**Comment by bbengfort** [comment]
Also you can check out:

https://lgtm.com/projects/g/DistrictDataLabs/baleen/

The review platform currently doesn't have any alerts, but potentially when we merge to master some will crop up.

**Comment by janetriley** [comment]
@bbengfort LGTM is asking for additional configuration to enable the pull request feature.  Glad to know about it, though.

**Comment by janetriley** [comment]
Merged to develop in [e622113](https://github.com/DistrictDataLabs/baleen/commit/e622113dee2b766fefb5567421663c4993c9c74a) ,  this ticket can be closed.
