### ISSUE TITLE
Move html sanitization to Post

### ISSUE THREAD

**Issue by janetriley** [bbengfort/baleen#87]
HTML sanitization functions are in the exporter and only applied at export. We may want to sanitize Posts in other situations.

Make Posts sanitizable and let the exporter ask for the level the user requested.

**Comment by bbengfort** [comment]
I really like how you did this in `htmlize()`!

**Comment by janetriley** [comment]
[Branch merged]( https://github.com/DistrictDataLabs/baleen/commit/88d5d7c57e7864bc50738726d5331b56c2c658df), closing the issue.
